### PR TITLE
Added Apache section to complete document.

### PR DESCRIPTION
**Pull request by jsuriol**

### CODE REVIEW

**Comment by childers** [comment]
Should this PR be against NAL-i5K/django-blast instead?

**Comment by childers** [comment]
It looks like this pull request is meant for the NAL-I5K fork of the code.

**Comment by childers** [comment]
I think you meant to issue this pull request to NAL-i5K:master, not hotdogee:master?

**Comment by jsuriol** [comment]
Opened in error, sorry. Closed

**Comment by jsuriol** [comment]
It's from way back.   Opened in error, sorry.  Now closed.

**Pull request closed without merging**
